language: bash
services: docker

env:
  - VERSION=3.4
  - VERSION=3.3

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="$(awk '$1 == "FROM" { print $2; exit }' passenger/Dockerfile)"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"
  - travis_retry docker build -t "$image-passenger" passenger
  - ~/official-images/test/run.sh "$image-passenger"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
