language: bash
services: docker

env:
  - VERSION=4.1
  - VERSION=4.1/alpine
  - VERSION=4.0
  - VERSION=4.0/alpine
  - VERSION=3.4
  - VERSION=3.4/alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "$VERSION"
  - image="redmine:${VERSION//\//-}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
      if [ -d passenger ]; then
        docker build -t "$image-passenger" passenger
        ~/official-images/test/run.sh "$image-passenger"
      fi
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
